import type { ReactElement } from "react";
import Layout from "../components/layout";
// import NestedLayout from '../components/nested-layout';
import type { NextPageWithLayout } from "./_app";
import Head from "next/head";
import { useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";

const Dashboard: NextPageWithLayout = () => {
  const { user, isSignedIn } = useUser();

  if (!user) {
    return <p>Loading user...</p>;
  }

  const { data: team } = api.goals.getTeamForUser.useQuery({
    userId: user.id,
  });

  return (
    <>
      <Head>
        <title>{"Dashboard | " + team?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Dashboard;

Dashboard.getLayout = function getLayout(page: ReactElement) {
    return <Layout>{page}</Layout>;
  };
